# Generated by Django 3.1.1 on 2021-03-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_ID',
            new_name='name',
        ),
    ]
