# Generated by Django 3.1.1 on 2021-03-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210309_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
