# Generated by Django 3.1.1 on 2021-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='approve',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
