# Generated by Django 3.1.1 on 2021-03-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_auto_20210311_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Halls',
        ),
    ]
