# Generated by Django 3.1.1 on 2021-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_delete_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hall_name',
            field=models.IntegerField(choices=[(1, 'Mini Audi'), (2, 'AG-01'), (3, 'AG-02')], default=1),
        ),
    ]
