# Generated by Django 3.1.1 on 2021-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_application_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hall_name',
            field=models.CharField(choices=[('Mini Audi', 'Mini Audi'), ('AG-01', 'AG-01'), ('AG-02', 'AG-02')], default='Mini Audi', max_length=150),
        ),
    ]
